apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: ollama
  labels:
    type: local
    app: postgres
    version: v1.0
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
