apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ollama
  labels:
    version: v1.0
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5432
    name: http-5432
    protocol: TCP
    targetPort: 5432