apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: ollama
  labels:
    version: v1.0
type: Opaque
data:
  # use base64 encoded values
  N8N_ENCRYPTION_KEY: "c3VwZXItc2VjcmV0LWtleQo="
  N8N_USER_MANAGEMENT_JWT_SECRET: "ZXZlbi1tb3JlLXNlY3JldAo="
  POSTGRES_PASSWORD: "cG9zdGdyZXNwYXNzd29yZA=="
