apiVersion: v1
kind: Secret
metadata:
  name: bolt-ai-secrets
  namespace: bolt-ai
  labels:
    version: v1.0
type: Opaque
data:
  GROQ_API_KEY: Cg== #<base64 encoded GROQ_API_KEY>
  OPENAI_API_KEY: Cg== #<base64 encoded OPENAI_API_KEY>
  ANTHROPIC_API_KEY: Cg== #<base64 encoded ANTHROPIC_API_KEY>
  OPEN_ROUTER_API_KEY: Cg== #<base64 encoded OPEN_ROUTER_API_KEY>
  GOOGLE_GENERATIVE_AI_API_KEY: Cg== #<base64 encoded GOOGLE_GENERATIVE_AI_API_KEY>
  
