apiVersion: v1
kind: Service
metadata:
  name: bolt-ai-service
spec:
  selector:
    app: bolt-ai
  ports:
  - protocol: TCP
    port: 5173
    targetPort: 5173
  type: ClusterIP # or NodePort, depending on your needs
