apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qdrant-storage-pvc
  namespace: ollama
  labels:
    version: v1.0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi